name: build
on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:      
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Setup Wing
        run: npm i -g winglang@latest
      - name: Install dependencies
        run: npm install
      - name: Test
        run: npm run test
      - name: Pack
        run: npm run pack
      - name: Publish
        run: npm publish *.tgz
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
